services:
  db:
    image: postgres:16-alpine
    container_name: 69-s1-db
    ports:
      - "54327:5432"
    enviroment:
      - POSTGRES_PASSWORD=isyl]y[
      - POSTGRES_USER=Theerachut
      - POSTGRES_DB=Theerachut
    volumes:
      - ./data:/var/lib/postgresql/data
      
