services:
  db:
    image: postgres:16-alpine
    container_name: 69-s1-db
    ports:
      - "54327:5432"
    environment:
      - POSTGRES_PASSWORD=isyl]y[
      - POSTGRES_USER=Theerachut
      - POSTGRES_DB=Theerachut
    volumes:
      - ./data-postgres:/var/lib/postgresql/data
  admin:
      image: dpage/pgadmin4
      container_name: 69-s1-admin
      environment:
        - PGADMIN_DEFAULT_EMAIL=theerachut@admin.com 
        - PGADMIN_DEFAULT_PASSWORD=pass2468      
      ports:
        - "8081:80" 
      depends_on:
        - db
volumes:
       -  ./data:/var/lib/pgadmin
